### ISSUE TITLE
Regression in 4.9.1 with merged profiles?

### ISSUE THREAD

**Issue by smitch88** [krakenjs/nemo#56]
I seem to be experiencing a new error with nemo `4.9.1` that I do not see in `4.6.0` or `4.9.0` for that matter.

The error I get is given below. It seems to stem from having a `mocks` profile defined that has a different defined `data` and `env` field than the `base` profile defines. Particular variables are not being merged into the map appropriately after the upgrade or thats what it looks like anyway. In my case specifically this causes a call to `nemo.data.baseUrl` in a spec to return `undefined` where in previous versions it seemed to contain a proper merge, maybe by coincidence it worked before?

#### Output Error
```
{ WebDriverError: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
  (Session info: headless chrome=70.0.3538.110)
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.13.6 x86_64)
URL when there was an error: data:,
    at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
    at propagateAslWrapper (node_modules/async-listener/index.js:504:23)
    at node_modules/async-listener/glue.js:188:31
    at node_modules/async-listener/index.js:541:70
    at node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at process.fallback (node_modules/async-listener/index.js:565:15) name: 'WebDriverError', remoteStacktrace: '' }
```

#### config.json
```
{
  "plugins": {
    "view": {
      "module": "nemo-view",
      "arguments": ["path:locators"]
    },
    "jaws": {
      "module": "nemo-jaws",
      "arguments": ...
    },
    "assert": {
      "module": "path:./plugins/nemo-assert"
    },
    "cookie": {
      "module": "path:./plugins/nemo-cookie"
    },
    "context": {
      "module": "path:./plugins/nemo-context"
    },
    "window": {
      "module": "nemo-window2"
    },
    "browser": {
      "module": "path:./plugins/nemo-browser"
    }
  },
  "data": {
    "baseUrl": "env:baseUrl",
    "targetHost": "env:targetHost",
    "testDataFilePath": "path:./testData/",
    "emailPrefix": "env:emailPrefix"
  },
  "output": {
    "reports": "path:reports"
  },
  "profiles": "exec:./config/profiles"
}
```

#### profiles.js
Some vars removed due to sensitivity
```
const path = require('path');
const minimist = require('minimist');

module.exports = function() {
  const argv = minimist(process.argv.slice(2));
  const defaultHost = '<host-here>';
  const driverPerTest = argv.driverPerTest || false;

  // Check for overrides in environment variables and command line args
  const targetHostOverride = argv.targetHost || process.env.targetHost;
  const baseUrlOverride = argv.baseUrl || process.env.baseUrl;
  const targetServerOverride = argv.targetServer || process.env.targetServer;

  const env = {
    SELENIUM_PROMISE_MANAGER: 0,
    targetHost: targetHostOverride || defaultHost,
    baseUrl: baseUrlOverride || `<base-url-here>`,
    // other args
  };

  return {
    base: {
      tests: argv.testsPath
        ? path.resolve(__dirname, `../${argv.testsPath}/**/*.js`)
        : path.resolve(__dirname, '../spec/**/*.js'),
      driverPerTest,
      env,
      mocha: {
        timeout: argv.mochaTimeout || 600000,
        require: ['@babel/polyfill', '@babel/register'],
        grep: argv.grep,
        reporter: argv.reporter || 'mochawesome',
        reporterOptions: { enableCode: false },
      },
      driver: {
        browser: argv.targetBrowser || 'chrome',
      },
      maxConcurrent: argv.maxConcurrent || 1,
    },
    local: {
      mocha: {
        reporterOptions: { autoOpen: true },
      },
    },
    mocks: {
      mocha: {
        timeout: 600000,
        require: [
          '@babel/polyfill',
          '@babel/register',
          path.resolve(__dirname, '../config/mock-setup.js'),
        ],
        reporter: 'xunit',
        delay: true,
        grep: argv.grep,
      },
      tests: path.resolve(__dirname, '../spec/mocks/**/*.js'),
      env: {
        SELENIUM_PROMISE_MANAGER: 0,
        targetHost: targetHostOverride || 'localhost',
        baseUrl: baseUrlOverride || 'http://localhost:9000',
        data: process.env.data || '{}',
      },
      driver: {
        browser: 'chrome',
        serverCaps: {
          chromeOptions: {
            args: ['headless', 'no-sandbox', 'disable-gpu', 'window-size=1200,800'],
          },
        },
        server: targetServerOverride,
      },
    },
  };
};
```

**Comment by grawk** [comment]
Hi @smitch88 .. Apologies if there is a regression in `4.9.1` .. your usage may represent an edge case I hadn't considered .. Can you please help explain in more detail your use case?

I.e.

- what arg(s) are you using on the command line
- how do you expect the missing property `baseUrl` to "flow" to your test (per your understanding)
- can you copy or approximate the relevant portions of the test file where you are accessing the property?

**Comment by grawk** [comment]
Close due to inactivity.. Please re-open with details if necessary.
